# Generated by Django 3.1.2 on 2020-10-03 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconsulta', '0002_auto_20201003_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 6, 42, 75632), verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 6, 42, 72641), verbose_name='Hora'),
        ),
    ]
