# Generated by Django 3.1.2 on 2020-10-03 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora',
            field=models.TimeField(default=datetime.time(13, 1, 43, 207424), verbose_name='Hora'),
        ),
    ]
